### ISSUE TITLE
DPL-005 DEPRECATED - BUG -  84 mismatching sample uuid and lighthouse uuid

### ISSUE THREAD

**Issue by harrietc52** [sanger/unified_warehouse#231] opened 2021-05-05 15:58 UTC
**Describe the bug**
As found in #220, there are 84 samples (prod_data on 05.05.21) where the uuid of the lighthouse sample doesnt match the uuid of the sample

**To Reproduce**

```sql
select root_sample_id from lighthouse_sample
        INNER JOIN
    stock_resource ON stock_resource.labware_human_barcode = lighthouse_sample.plate_barcode
        AND stock_resource.labware_coordinate = lighthouse_sample.coordinate
        INNER JOIN
    sample ON sample.id_sample_tmp = stock_resource.id_sample_tmp
        AND lighthouse_sample.root_sample_id = sample.description
        AND lighthouse_sample.result = sample.phenotype 
WHERE
    lighthouse_sample.id >= 0
        AND lighthouse_sample.lh_sample_uuid <> sample.uuid_sample_lims;

```

**Contacts**
Phil
Eduardo
Harry

**Expected behaviour**
We expect all samples and lighthouse samples to have the sample uuid. 
Take sample uuid as the single source of truth

**Additional context**
May be work looking back at query which updated the uuid's originally

**Comment by harrietc52** [comment] 2021-05-10 15:29
Uuid -
Using it to find mismatching cog uk id
Compare with old join gave mismatch of 85 samples (83 of which are duplicates based on old join)
Solution? Delete one of the duplicate plates
TODO: investigate final 2 samples

We think this is due to the join on stock resource only accessing Sentinel plates, ignoring Beckman sources

**Comment by idwright** [comment] 2021-05-25 09:25
FYI - the coordinate in stock resource and lighthouse_sample are not 100% consistent - sometimes they are left padded e.g. A01 and sometimes not e.g. A1 - can be different in each place

This is my current best guess:

```
    CASE
        WHEN sample.name LIKE 'Heron%'
        AND NOT (
            stock_resource.labware_human_barcode LIKE 'DN%'
            OR stock_resource.labware_human_barcode LIKE 'HT%'
        ) THEN CONCAT(
            stock_resource.labware_human_barcode,
            '_',
            SUBSTRING(stock_resource.labware_coordinate, 1, 1),
            IF(stock_resource.labware_human_barcode IN ('002220346', '002220432', '002220433', '002220436', '002220437', '002220440', '002220441', '002221688', '002221689', '002318059', '002318138', '002318139', '002318140', '002318141', '002318143', '002318145', '002318147', '002319670', '002319671', '002319672', '002319673', '002319674', '002319675', '002319676', '002319678', '002319679', '002319680', '002319682', '002319683', '002319685', '002319691', '002319692', '002319693', '002319996', '999925546', 'CBE000029', 'CBE000369', 'CBE000370', 'CBE000371', 'CBE000372', 'CBE000373', 'CBE000374', 'CBE000375', 'CBE000376', 'CBE000377', 'CBE000378', 'CBE000394', 'CBE000395', 'CBE000396', 'CBE000398', 'CBE000477', 'CBE000478', 'EGC000201','002318149', '002319686', '002319687','002318146'), SUBSTRING(stock_resource.labware_coordinate, 2),
            LPAD(SUBSTRING(stock_resource.labware_coordinate, 2), 2, '0'))
        )
        WHEN sample.name NOT LIKE 'Heron%' THEN sample.name
    END as calculated_rna_id,
```

**Comment by KatyTaylor** [comment] 2021-09-08 13:54
Running the query in the description today gave 1193 rows, but I think this is expected, as there are some samples that got imported into Sequencescape via both Sentinel and Beckman processes - the 1193 here are presumably the ones where we chose to link the uuid to the samples imported via Beckman (see https://github.com/sanger/unified_warehouse/issues/234 and https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Duplicate+COG+UK+IDs+May+2021).

I think we can close this story as 
a) it is unclear from the description quite what the problem is, and 
b) I believe the '84' samples mentioned in the description and Harry's comment probably map to the "'Double click' duplicates" referred to on this Confluence page - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Duplicate+COG+UK+IDs+May+2021 - which were already dealt with.

**Comment by KatyTaylor** [comment] 2021-09-08 14:09
> FYI - the coordinate in stock resource and lighthouse_sample are not 100% consistent - sometimes they are left padded e.g. A01 and sometimes not e.g. A1 - can be different in each place
> 
> This is my current best guess:
> 
> ```
>     CASE
>         WHEN sample.name LIKE 'Heron%'
>         AND NOT (
>             stock_resource.labware_human_barcode LIKE 'DN%'
>             OR stock_resource.labware_human_barcode LIKE 'HT%'
>         ) THEN CONCAT(
>             stock_resource.labware_human_barcode,
>             '_',
>             SUBSTRING(stock_resource.labware_coordinate, 1, 1),
>             IF(stock_resource.labware_human_barcode IN ('002220346', '002220432', '002220433', '002220436', '002220437', '002220440', '002220441', '002221688', '002221689', '002318059', '002318138', '002318139', '002318140', '002318141', '002318143', '002318145', '002318147', '002319670', '002319671', '002319672', '002319673', '002319674', '002319675', '002319676', '002319678', '002319679', '002319680', '002319682', '002319683', '002319685', '002319691', '002319692', '002319693', '002319996', '999925546', 'CBE000029', 'CBE000369', 'CBE000370', 'CBE000371', 'CBE000372', 'CBE000373', 'CBE000374', 'CBE000375', 'CBE000376', 'CBE000377', 'CBE000378', 'CBE000394', 'CBE000395', 'CBE000396', 'CBE000398', 'CBE000477', 'CBE000478', 'EGC000201','002318149', '002319686', '002319687','002318146'), SUBSTRING(stock_resource.labware_coordinate, 2),
>             LPAD(SUBSTRING(stock_resource.labware_coordinate, 2), 2, '0'))
>         )
>         WHEN sample.name NOT LIKE 'Heron%' THEN sample.name
>     END as calculated_rna_id,
> ```

@idwright did this ever get looked at? I've just looked for padded coordinates in lighthouse_sample coordinate column:
```
SELECT * 
FROM lighthouse_sample
WHERE coordinate LIKE '_0_'
LIMIT 10;
```
and in stock_resource coordinate column:
```
SELECT * 
FROM lighthouse_sample
WHERE coordinate LIKE '_0_'
LIMIT 10;
```
and couldn't find any.

If you were looking at the rna_id column in lighthouse_sample, we would expect this to contain padded coordinates as this is how we receive them from the lighthouse labs. Are you happy for me to treat this as resolved ?
Thanks

**Closed** 2024-10-08 07:44 UTC
Labels: Bug, On hold
