### ISSUE TITLE
GPL-859 join between lighthouse_sample and sample

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/unified_warehouse#184] opened 2021-02-11 15:28 UTC
**User story**
As someone needing to report on Heron samples, I would like there to be an easy and quick way to join between the lighthouse_sample table and the sample table.

At time of writing, the options are:

lighthouse_sample | sample | comments
-- | -- | --
cog_uk_id | supplier_name | only for samples that have cog uk ids assigned
root_sample_id | description | description is a long field and can't be indexed, root sample id is not unique
root_sample_id, plate_barcode, coordinate | description, stock_resource table labware_human_barcode and labware_coordinate | convoluted, slow, not user friendly [Not viable, stock resource plate is the cherrypick plate not the source plate, see comments]
lh_sample_uuid | uuid_sample_lims | only for samples that have gone through Beckman cherrypicking process

Suggestion:
Add indexes to cog_uk_id and supplier_name (this is being done by Eduardo at time of writing for a different story)
Consider back-populating uuids for samples, and mechanism to make these match up for non-Beckman samples going forward.

**Who are the primary contacts for this story**
Jeff B, PaM

**Additional context**
Came out of Slack question by Jeff B on 11th Feb needing to run a quick query.
("It would be great if it could go as a request somewhere. It is medium urgency, as I don’t have to run the query fast usually, was just needing something quick today.")

**Comment by JamesGlover** [comment] 2021-02-11 15:51
Indexes: https://github.com/sanger/unified_warehouse/issues/139

**Comment by JamesGlover** [comment] 2021-02-11 16:03
Indexes were completed quickly on 12th November, but merging was missed. At the time I was aware of delays due to the sample extraction tables UAT, but other warehouse changes went live on the 14th December. It appears I realised the merge hadn't occurred on the 18th December, and merged in then. No release was made, probably due to proximity to Christmas.

Issue wasn't on the heron board, so no easy visibility of lack of 'Done'

**Comment by emrojo** [comment] 2021-02-11 16:49
Adding cog_uk_id index: 

https://github.com/sanger/unified_warehouse/pull/185

**Comment by idwright** [comment] 2021-02-12 13:48
Some comments based on the table above:

You can't join on the stock_resource table as, after Beckman?, the plate doesn't match between that and lighthouse_sample

There can be multiple rows per sample in lighthouse_sample if the plate map has been updated so you need to get the most recent version - this can flip the result so it's important

As it says root_sample_id isn't always unique - there can be multiple wells with the same root_sample_id either on the same plate or different plates

lighthouse_sample.rna_id is a good one to use (not unique because of updated plate maps) but there's nothing at the sample side to join to - see stock_resource comment

**Comment by idwright** [comment] 2021-02-22 10:26
Please see https://rt.sanger.ac.uk/SelfService/Display.html?id=713096

**Comment by stevieing** [comment] 2021-02-23 13:45
Task 1 - Add index to cog_uk_id but first check if the data is unique. This will need to be done out of hours due to the time it will take.

**Comment by stevieing** [comment] 2021-02-23 13:46
Task 2 - Get a sandbox for the relevant tables in the warehouse so we can experiment with different techniques to speed up the queries. We can use examples provided by @idwright.

**Comment by stevieing** [comment] 2021-02-23 13:47
Task 3 - Use the sandbox with the queries provided by @idwright to see if there is any way to speed things up with no architectural changes.

**Comment by stevieing** [comment] 2021-02-23 13:50
Task 4 - Using the results of the investigation from above there are two different things we can try:

- joining on the lh sample uuid in lighthouse sample and uuid in the sample table
- joining on the cog uk id

**Comment by stevieing** [comment] 2021-02-23 13:52
Task 5 - If we decide to use the uuid we will need to ensure:

- the join is being done in the most efficient way possible
- we will need to back populate uuid for samples. This may need to be done in 2 stages depending on how much data is needed

**Comment by stevieing** [comment] 2021-02-23 13:59
Task 6 - Depending on the results of the above create a research story to see if we could make any architectural changes to the crawler process. One of the main challenges is that the crawler process inserts duplicate rows for various reasons. One caveat is that the new process for plate maps only containing one plate may counteract this problem.

**Comment by stevieing** [comment] 2021-02-23 16:35
I have done some initial investigation on the lighthouse samples table. It is painfully slow. Even finding a single cog uk id takes ~60s. Sods law we have 1 duplicate BIRM-64125 on the same plate in a different well.

**Comment by andrewsparkes** [comment] 2021-02-23 17:11
Is that a bug in the code, shouldn't two instances of the same sample in different wells of a plate get different Cog Uk Ids?

**Comment by cs46** [comment] 2021-02-25 13:07
Just to add that this is becoming an issue for my team as well, we are having to do workarounds that are less than ideal.

**Comment by idwright** [comment] 2021-02-26 09:59
See also https://rt.sanger.ac.uk/SelfService/Display.html?id=713491

cog_uk_id is not being filled in on lighthouse_sample and the plates from stock_resource and lighthouse_sample don't match

Combined with not being able to tell the latest row in lighthouse_sample for a given root_sample_id, this is a real problem

**Comment by andrewsparkes** [comment] 2021-02-26 15:15
The cog_uk_id is currently only filled in on lighthouse_sample for samples that have been cherrypicked. As we store all the samples that are negatives as well as the high proportion of positives that don't get picked it would be a waste to generate cog barcodes for all the millions of lighthouse_sample rows.

The barcode on stock_resource is the created cherrypicked destination plate, the plates on lighthouse_sample are the source plate barcodes from the lighthouse, they aren't supposed to match. They are connected in the 'lh_beckman_cp_destination_created' type events in the MLHW Events database.

The latest row for a root_sample_id should be the one with the latest created_at timestamp. But the unique key on lighthouse_sample is a combination of root_sample_id, rna_id, result and lab_id.

**Comment by idwright** [comment] 2021-03-01 07:52
We need to be able to identify the correct, i.e. most recent, lighthouse_sample row for any given sample i.e. rna_id
It's not currently possible to do this i.e. using the the latest created_at timestamp gives lots of duplicates, it's better if you use the latest date_tested as well but that's still not unique and horrible for performance.

The use of the stock_resource table has changed - it used to be the plate_barcode of the incoming plate i.e. the same as the plate in lighthouse_sample - see https://github.com/sanger/General-Backlog-Items/issues/123
When the way that fields are populated/the interpretation of the data changes it (potentially) causes us problems
In this case it means that where there are duplicate root_ids for different rna_id on the lighthouse_sample then we can't link between the tables without then sometimes using the event table as well - this is getting really complicated just to join between two tables

I'm not expecting there to be a cog_uk_id on lighthouse_sample for samples which haven't been cherrypicked, the problem is that there are samples which have been cherrypicked, i.e. have a supplier_name on sample, where it's not populated on lighthouse_sample

**Comment by idwright** [comment] 2021-03-09 07:52
Another good example via @cs46 

1 root sample id/lighthouse_sample: AAI19503223 has 2 cog_uk_id/sample: redacted

There are lots of examples of the root_sample_id being used for different samples

**Comment by cs46** [comment] 2021-03-09 13:20
FYI there are roughly 830 samples where this has occurred.  This has been raised by PHS as I do not know which COG-UK ID to give them.  Has this problem become more widespread recently? @idwright

**Comment by idwright** [comment] 2021-03-11 08:40
Particularly with the Eagle samples what we really need is a view which returns one row per Heron sample bearing in mind that the samples can be in only lighthouse_sample, only sample or both

To be most efficient I think what this would need is:

- ids to enable efficient joining
- root_sample_id
- cog_uk_id
- sanger_sample_id
- sample.name
- sample.control
- sample.phenotype
- lighthouse_sample.result
- lighthouse_sample.filtered_positive
- date_tested
- sample.created
- incoming plate barcode (lighthouse_sample.plate_barcode or ???)
- lab_id
- lighthouse_sample.source
- sample.cohort

This would also make it easier to redesign tables for performance

**Comment by stevieing** [comment] 2021-03-12 11:29
From initial investigations changing the uuid columns in both lighthouse_sample and sample yielded a 30% increase in query speed doing a full table scan. Based on that I am going to spin this out to add support for creating uuids in the crawler for non-beckman samples

**Comment by rl15** [comment] 2021-03-16 09:05
Ian W wrote (Tuesday, 16 March 2021 at 08:46)

I've suggested a view at https://github.com/sanger/unified_warehouse/issues/184#issuecomment-796568442
This would give us what we want and allow performance improvements later without too much impact
(I don't think mysql supports materialized views)

While faster is always better we don't need it to be super quick - better to have something slow now and speed it up later than wait for a quicker query

**Comment by stevieing** [comment] 2021-03-17 09:12
![Uploading Whiteboard[1]-01.png…]()

**Comment by stevieing** [comment] 2021-03-17 09:17
Current setup for creating uuids:

![creating-uuids](https://user-images.githubusercontent.com/519327/111443799-a4879c80-8701-11eb-9b01-baba7384b202.png)

**Comment by idwright** [comment] 2021-03-18 09:06
Realised that the example `AAK52142173` isn't listed as part of this issue so adding it for clarity/ease of reference

This is the case where there are two identical root_sample_ids, both positive, one is marked as Eagle, the other not - one of the lighthouse_sample table entries has the cog_uk_id filled in, the other not (on sample one is positive, the other Positive)

A more straightforward one is `AAI45209861` where two root_sample_ids with different cog_uk_ids but both filled in on lighthouse_sample and neither Eagle

This duplicate issue is separate from where there are multiple plate map entries i.e. rna_id/root_sample_id the same

**Comment by andrewsparkes** [comment] 2021-03-18 10:00
Those examples are not duplicates as far as we are concerned.
AAK52142173 looks like it has been tested by 2 different lighthouses on 2 different days. Only one instance cherrypicked and sequenced so that one has a Cog Uk Id.  (Obviously could be an error on the Lighthouse side e.g. typo in one or the sample ids, but we cannot know that).
AAI45209861 was tested by the same Lighthouse twice on the same day in 2 different plates. Both instances sequenced and therefore 2 Cog UK Ids is correct.
The Lighthouses are able to test the same sample more than once, and Sanger sequence them as distinct samples, so that is reflected correctly in the lighthouse_sample data.
My feeling is the problem is more that we are trying to join to different types of data. The MLWH samples table is abstract sample information (physical samples are elsewhere in aliquots and receptacles tables), whereas lighthouse_sample represents physical samples received in plates.

**Comment by idwright** [comment] 2021-03-18 11:42
They are duplicates in as far as there are errors in the data

In order to report back to DHSC we need to be able to identify which cog_uk_id and therefore which sequence data maps back to which root_sample_id

(root_sample_id is supposed to be unique for a physical sample but it's not)

We need to be able to associate a record from the sample table with a record from the lighthouse_sample table - previously we've used when the root_sample_id and cog_uk_id are both the same but we can't do that because:

1) Where there are multiple cog_uk_id associated with one root_sample_id
2) Where the cog_uk_id isn't filled in on lighthouse_sample

If you try and do it based just off the root_sample_id then it doesn't work because there are (erroneously) multiple physical samples (rna_id) associated with the same root_sample_id

You can't do with the cog_uk_id for reasons above

You can sometimes do it by using the plate barcode and well from stock_resource but that doesn't work for all samples because it sometimes refers to a different plate (DN or HT instead of the lighthouse_sample plate) i.e. it doesn't give you any more than the root_sample_id/cog_uk_id combo

That's without even taking into account where there are multiple rows in lighthouse_samples because there are multiple plate map entries for the same plate/well (you can get all three results depending on which plate map entry is used - result should not be part of the unique constraint)
 
Presumably the record in the sample table is created by selecting a 'filtered_positive' record from lighthouse_sample so we need to make sure that relationship is captured

**Closed** 2021-04-21 09:04 UTC
Labels: Reporting
